GET http://localhost:3042/items HTTP/1.1
###

POST http://localhost:3042/item HTTP/1.1
content-type: application/json

{
    "taskName": "30,    34"
}

###


PUT http://localhost:3042/item HTTP/1.1
content-type: application/json

{
    "id": "71",
    "done" : "{{$localDatetime rfc1123}}",
    "status": true
}
###

DELETE http://localhost:3042/item HTTP/1.1
content-type: application/json

{
    "id": "1"
}